### PR TITLE
Make caller enforce invariants when setting AES encryption key

### LINKED ISSUE #113: AES_set_encrypt_key and variants return error codes, but they are ignored
Look at https://github.com/briansmith/ring/blob/80400f5fdfb3765acd490801c66ddf30d3dc6378/crypto/cipher/e_aes.c#L152 and other instances where those functions are called. The return value is ignored. It seems like the functions will never fail if given valid inputs, so they should have their return types changed to `void`. 

However, some variants aren't so clear as to whether they can fail on valid inputs or not. For example, `asm_AES_set_encrypt_key`/`_armv4_AES_set_encrypt_key` have code to jump to `.Labrt`. Is this just the "verify inputs are not null" check? If so, that code can be removed.

Note that in BoringSSL, but not OpenSSL, it is assumed that input parameters are not NULL unless the function's documentation specifically states they may be NULL, and NULL checks on parameters are not done.

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #113.

`GFp_AES_set_encrypt_key` can fail if and only if the following invariants are violated.

* All pointer arguments must be non-null.
* The key size must be either 128 or 256 bits (192 bit keys [aren't supported](https://github.com/briansmith/ring/commit/b3e91be71edde28f5d2884d3c3c34260b6a79378)).

The first invariant should not be checked at runtime (except via assertion) as it is the responsibility of the caller.

The second could be expressed statically by accepting an enum with the valid key lengths, but enums don't provide any type safety in C. Instead, we document the acceptable key lengths and make them the responsibility of the caller.

As a result of these changes, `GFp_AES_set_encrypt_key` (as well as `GFp_aes_c_set_encrypt_key`) no longer needs to return an error code. The assembly functions still return an error code and do input validation.

### CODE REVIEW

File: crypto/fipsmodule/cipher/e_aes.c [hunk 1]
```diff
@@ -237,9 +244,12 @@ int GFp_aes_gcm_init(uint8_t *ctx_buf, size_t ctx_buf_len, const uint8_t *key,
     return 0;
   }
 
-  // XXX: Ignores return value. TODO: These functions should return |void|
-  // anyway.
-  GFp_AES_set_encrypt_key(key, (unsigned)key_len * 8, &ks);
+  unsigned bits = key_len * 8;
+  if (bits != 128 && bits != 256) {
```
Comment (briansmith) [inline crypto/fipsmodule/cipher/e_aes.c]: Instead, let's compare `key_len != 16 && key_len != 32` so we don't have to worry about any overflow issues with the multiplication.

File: crypto/fipsmodule/aes/aes.c [hunk 2]
```diff
@@ -323,16 +315,18 @@ int GFp_aes_c_set_encrypt_key(const uint8_t *key, unsigned bits,
       rk[6] = rk[2] ^ rk[5];
       rk[7] = rk[3] ^ rk[6];
       if (++i == 10) {
-        return 0;
+        return;
       }
       rk += 4;
     }
   }
+
```
Comment (briansmith) [inline crypto/fipsmodule/aes/aes.c]: set `aeskey->rounds = 14;` here.

File: crypto/fipsmodule/aes/aes.c [hunk 3]
```diff
@@ -323,16 +315,18 @@ int GFp_aes_c_set_encrypt_key(const uint8_t *key, unsigned bits,
...
   rk[4] = from_be_u32_ptr(key + 16);
   rk[5] = from_be_u32_ptr(key + 20);
   rk[6] = from_be_u32_ptr(key + 24);
   rk[7] = from_be_u32_ptr(key + 28);
   if (bits == 256) {
```
Comment (briansmith) [inline crypto/fipsmodule/aes/aes.c]: Remove the `if (bits == 256) {` here and do this unconditionally.

**Comment by ecstatic-morse** [comment]
If/when this gets merged, the equivalent [error handling](https://github.com/briansmith/ring/blob/9814ac47dff08424dd75e31881e7ba257880a096/crypto/fipsmodule/aes/asm/aes-x86_64.pl#L753-L756) [code](https://github.com/briansmith/ring/blob/9814ac47dff08424dd75e31881e7ba257880a096/crypto/fipsmodule/aes/asm/aes-x86_64.pl#L775-L776) should be removed from the assembly implementations. 

Also, 192-bit key support was removed from the [vectorized assembly](https://github.com/briansmith/ring/commit/1103cf29dfbbf51f0dd8fb757084caa052863869) but not the assembly using [AES-NI](https://github.com/briansmith/ring/blob/9814ac47dff08424dd75e31881e7ba257880a096/crypto/fipsmodule/aes/asm/aesni-x86_64.pl#L1196).

I can open new issues for these if you like.

File: crypto/fipsmodule/aes/aes.c [hunk 4]
```diff
@@ -323,41 +315,41 @@ int GFp_aes_c_set_encrypt_key(const uint8_t *key, unsigned bits,
...
       rk[7] = rk[3] ^ rk[6];
       if (++i == 10) {
-        return 0;
+        return;
       }
       rk += 4;
     }
   }
+
+  // bits == 256
```
Comment (briansmith) [inline crypto/fipsmodule/aes/aes.c]: This should be `assert(bits == 256);`. That is, we prefer checked (at debug time at least) assertions to unchecked assertions.

File: src/aead/aes_gcm.rs [hunk 5]
```diff
@@ -172,8 +174,8 @@ mod tests {
     }
 
     extern "C" {
-        fn GFp_AES_set_encrypt_key(key: *const u8, bits: usize,
```
Comment (briansmith) [inline src/aead/aes_gcm.rs]: We should have done this change as a separate commit. But, OK.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by briansmith** [comment]
@ecstatic-morse Are you still interested in this? It would be great if you could make the small changes I requested in the PR soon. I want to refactor the C code (or, if you want, you can do so, in another PR!) to remove the duplication between the 128-bit case and the 256-bit case, and to replace the weird loop constructions with straightforward `for` loops. I'd prefer to merge this PR before making those changes so that I don't create a merge conflict for you that you'd have to resolve manually.

**Comment by ecstatic-morse** [comment]
Sorry, life got in the way last week. I made the changes and squashed.

My plan was to start working on #660 and #705 tonight. Refactoring AES round key generation would be a nice warm up.

On a more meta note, I'm trying to get accustomed to the programming style here before I tackle more involved issues. If you have any suggestions for next steps, I'd love to hear them.

**Comment by ecstatic-morse** [comment]
I refactored the C AES key expansion routines [in this branch](https://github.com/ecstatic-morse/ring/blob/aes-key-expansion/crypto/fipsmodule/aes/aes.c). I'll submit a PR when this gets merged.

File: crypto/fipsmodule/cipher/e_aes.c [hunk 6]
```diff
@@ -132,15 +132,19 @@ int GFp_vpaes_set_encrypt_key(const uint8_t *userKey, unsigned bits,
...
   // Keep this in sync with |gcm128_init_gmult_ghash| and |aes_ctr|.
 
+  assert(user_key != NULL);
+  assert(key != NULL);
+  assert(bits == 128 || bits == 256);
+
 #if defined(HWAES)
   if (hwaes_capable()) {
-    return GFp_aes_hw_set_encrypt_key(user_key, bits, key);
+    GFp_aes_hw_set_encrypt_key(user_key, bits, key);
```
Comment (briansmith) [inline crypto/fipsmodule/cipher/e_aes.c]: Please prefix this with `(void)` to make it clear we're ignoring the return value intentionally.

File: crypto/fipsmodule/cipher/e_aes.c [hunk 7]
```diff
@@ -149,14 +153,15 @@ int GFp_AES_set_encrypt_key(const uint8_t *user_key, unsigned bits,
 #error "BSAES and VPAES are enabled at the same time, unexpectedly."
 #endif
   if (vpaes_capable()) {
-    return GFp_vpaes_set_encrypt_key(user_key, bits, key);
+    GFp_vpaes_set_encrypt_key(user_key, bits, key);
```
Comment (briansmith) [inline crypto/fipsmodule/cipher/e_aes.c]: Ditto: prefix with `(void)`.

**Comment by briansmith** [comment]
Thanks for the quick turnaround @ecstatic-morse. I was just about to merge this but I noticed a couple of things: (1) We are missing a couple places where we should be using `(void)`, and (2) You didn't add "I agree to license..." to the end of your commit message. Please update the commit with those changes and I'll merge ASAP.

**Comment by ecstatic-morse** [comment]
Whoops, sorry about that. I added the disclaimer to the commit message and made the requested changes.

Is the use `(void)` to explicitly ignore return values documented anywhere? I didn't see it in `STYLE.md`.

**Comment by briansmith** [comment]
Thanks!

No, I guess it isn't mentioned in the style guide. One reason is that it is unusual for us to ignore return values in the first place. We're only doing so here temporarily until the types of those functions change to be `void`.

FWIW, I'd normally write `(void)x` instead of `(void) x` but NBD.
